### ISSUE TITLE
Maza sa nhi aaya, kuch achha likh

### ISSUE THREAD

**Issue by darecoder** [urvashigupta7/DS-Algo-Practice#1]
DP karo DP

**Comment by urvashigupta7** [comment]
Sab krenge dheere dheere

**Comment by darecoder** [comment]
Toh karo na, Hum bhi pareshaan ho gye tum bhi pareshaan ho gye

**Comment by urvashigupta7** [comment]
Sab ek din me ni kr skti na😂

**Comment by darecoder** [comment]
![maze ](https://user-images.githubusercontent.com/42637982/74587972-a4a8fa80-501e-11ea-855a-79ccf9346a0a.jpeg)

**Comment by urvashigupta7** [comment]
Kr chuki hu phle bhi  revising it again.. Aur ab apki pitayi hine vli hai
